### ISSUE TITLE
Cannot read properties of undefined (reading 'getFields')

### ISSUE THREAD

**Issue by jameskenyon** [Lorenzohidalgo/serverless-gql-generator#2]
Hey @Lorenzohidalgo!

We'd love to check out this tool you've built but after following the setup instructions provided we are getting the following error when deploying to Serverless:

```
Cannot read properties of undefined (reading 'getFields')
```

Unfortunately there isn't much more context but please let me know if we can provide any more information to help you debug!

**Comment by Lorenzohidalgo** [comment]
Hey @jameskenyon, thanks for opening this issue.

Would you be able to provide a sample schema that's similar to the one you're using? 

Do you see any more information or context when you trigger one of the following:
```
serverless gql-generator validate-schema
or
serverless gql-generator generate
```

**Comment by jameskenyon** [comment]
Unfortunately I'm not able to share the schema as it's confidential, apologies for the inconvenience. 
I have tried running both of the above commands with the following results: 

`serverless gql-generator validate-schema`: I get the message: `✔ GraphQL Schema Validated`
`serverless gql-generator generate`: Get the message `Error:
Cannot read properties of undefined (reading 'getFields')`

**Comment by Lorenzohidalgo** [comment]
Thanks for the info @jameskenyon!

I've created multiple schemas to test the specific parts of the code that could throw this error but I'm not able to reproduce it.

Can you create a new schema that is similar to the one you used or provide more details into if you're using any special directive/feature? I'd need some kind of hint to continue debugging this

It would also work if you try removing some parts of the schema while triggering `serverless gql-generator generate` to isolate the root cause and that way you would only need to provide that part of the schema.

**Comment by Lorenzohidalgo** [comment]
Could you also provide the configuration you're using for the plugin? (all fields under the `gql-generator:`)

**Comment by jameskenyon** [comment]
Thanks so much for being so active with this @Lorenzohidalgo! 

We are using some AWS auth directives which could potentially be the cause? For example,
`@aws_cognito_user_pools`, `@aws_api_key`, ... See [this](https://docs.aws.amazon.com/appsync/latest/devguide/security-authz.html) article for a complete list. We also use the `@deprecated` directive, which I assume you have already supported? Additionally, we use quite a few comments denoted with `#` - just thought I'd mention in case your parsing doesn't take these into account? 

If you think that these are not likely the cause of the problem then I'll try what you have suggested by isolating different parts of our schema in order to try and find the problematic components.

In terms of the additional configuration we have under `gql-generator:`, I haven't configured this as the defaults looked sufficient. If there are any options you think might help just let me know and I can test this out. 

Thanks again!

**Comment by Lorenzohidalgo** [comment]
Hi @jameskenyon,

I've retested with schemas containing the provided details and am still unable to reproduce the error.

Would really appreciate it if you could try to isolate/pinpoint what part of your schema is breaking the logic.

I plan to publish a fix once I'm able to reproduce the error.
